### ISSUE TITLE
Laravel 5.4 "Invalid argument supplied for foreach()"

### ISSUE THREAD

**Issue by kilrizzy** [creativeorange/gravatar#12]
Not sure if it's 5.4 specific but adding to a new project gave me:

"Invalid argument supplied for foreach()" pointing to \Illuminate\Support\Arr.php

Traced it down and looked like it just required me to make my the "default" entry in my gravitar config file an array instead of string:

`'default' => 'identicon',`

becomes:

`'default' => ['identicon'],`

**Comment by zymawy** [comment]
Thank You For The Tip. @creativeorange Consider This Issue Please.
