### ISSUE TITLE
Fallback does not work; functions are not used

### ISSUE THREAD

**Issue by ryancwalsh** [creativeorange/gravatar#13]
`Gravatar::fallback($googleMapsImgUrl)->get($dbContact->emailAddress);` does not seem to use the fallback URL at all.

In fact, my Netbeans IDE shows that none of these functions in `Gravatar.php` get used at all:

- `sizeParameter`
- `defaultParameter`
- `ratingParameter`
- `forceDefaultParameter`

`Gravatar::exists($emailAddress)` and `Gravatar::get($emailAddress)` seem to work, though, so I'm using those. 

Thanks! :-)

P.S. I recommend also adding in your setup instructions that `use Gravatar;` should be added at the top of whatever file we're calling it from. It took me a long time to figure that out. I was even accidentally trying `use Creativeorange\Gravatar\Facades\Gravatar;`, which didn't work.

**Comment by creativeorange** [comment]
Hi ryan,

Thanks for the feedback. I will take a look at this in the coming week.

Jaco
