### ISSUE TITLE
V1.0.10 not really loading

### ISSUE THREAD

**Issue by bestmomo** [creativeorange/gravatar#16]
Hello

When I install the package with composer it says that it installs the V1.0.10, but when I look at the vendor I see that **composer.json** doesn't have the discovery option for Laravel 5.5. So this is not the last version that is uploaded. I made the intallation many times and always the same result even if I clear composer cache...

**Comment by RalphMRivera** [comment]
Auto discovery is not working for me either.

**Comment by mvdnbrk** [comment]
The latest release with auto discovery is tagged as V1.0.10.
Packagist point to [1.0.10](https://github.com/creativeorange/gravatar/releases/tag/1.0.10) (without the v prefix) wich is another release.
