### ISSUE TITLE
Use HTTPS all the time

### ISSUE THREAD

**Issue by joshlewis** [creativeorange/gravatar#17]
This library should just use HTTPS all the time for Gravatar. There's no reason not to. Using HTTPS inside of a site that is currently using HTTP doesn't cause any problems, but clearly the reverse is not true. 

HTTPS forever! 😉

**Comment by brainpink** [comment]
Hi Josh,

Thanks for the feedback! I’ve scheduled an update for the end of this month and I will update this package to only use HTTPS connections only. I totally agree: HTTPS forever!

Verstuurd vanaf mijn iPhone

**Comment by joshlewis** [comment]
By the way, I'm more than happy to open a pull request for this. Let me know if you'd like me to.

**Comment by brainpink** [comment]
Yes please :)

Verstuurd vanaf mijn iPhone

**Comment by brainpink** [comment]
Thanks!
