### ISSUE TITLE
checkEmail() function cause a validation problem

### ISSUE THREAD

**Issue by mkovtun-smartech** [creativeorange/gravatar#19]
`private function checkEmail($email)` use `filter_var()` function with **FILTER_VALIDATE_EMAIL** as a second parameter. This is a problem because Laravel's email validator use different check for email.
For example Laravel consider `maxim@localhost` as a valid email, but FILTER_VALIDATE_EMAIL does not.

Please, consider to change filter_var() with FILTER_VALIDATE_EMAIL to standard Laravel 'email' validator

**Comment by rocramer** [comment]
True, this causes trouble for lots of email addresses because the  `FILTER_VALIDATE_EMAIL` is too strict. 

Would you consider a PR that fixes the problem? @creativeorange

**Comment by jacotijssen** [comment]
Hi @rocramer 
Sure, please create a PR and I will merge it ASAP. Thanks
