### ISSUE TITLE
Gravatar::fallback()

### ISSUE THREAD

**Issue by afoysal** [creativeorange/gravatar#28]
I am using like below

`$data['gravatar'] 	= (!empty(auth()->user()->email)) ? Gravatar::fallback(url('images/user.jpg'))->get(auth()->user()->email) : null;`

But why my output is like below ? 

`<img id="userImg" class="userImg" src="https://secure.gravatar.com/avatar/a516098e1de8e2756fa4bf045c7a4cb2.jpg?s=150&amp;d=http%3A%2F%2F127.0.0.1%3A8000%2Fimages%2Fuser.jpg&amp;r=g" alt="user">`

Could anyone help me in this regard ?

**Comment by brainpink** [comment]
Fixed in v1.0.19 ( #27 )
