### ISSUE TITLE
Laravel 5.2 bindShared deprecated

### ISSUE THREAD

**Issue by christophrumpel** [creativeorange/gravatar#4]
Hey,

just upgraded my application to Laravel 5.2, but I get an error because of this deprecated function "bindShared". (http://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)

Is this package really ready for Laravel 5.2? Could you update the package?

Cheers
Christoph

**Comment by creativeorange** [comment]
Hi Christoph,

Sorry for the inconvenience. I've updated the package to v1.0.8. Could you please try again?

Cheers,

Jaco

**Comment by christophrumpel** [comment]
Ah great, yes now it si workin. Thanks a lot! For the package too :-)
