### ISSUE TITLE
config/gravatar.php ignored on server

### ISSUE THREAD

**Issue by smalomo** [creativeorange/gravatar#5]
The settings file (vendor/creativeorange/gravatar/config/gravatar.php) is not being applied to the production site because the vendor directory is in .gitignore so as soon as the site is deployed, the default settings are installed.

Is there a way to have the gravatar.php config file inside the app/config directory as some other vendor settings are?

**Comment by creativeorange** [comment]
`php artisan vendor:publish --provider="Creativeorange\Gravatar\GravatarServiceProvider"` will copy the configuration file in to your apps config directory and your app will use that file.
