### ISSUE TITLE
Exists always returns true

### ISSUE THREAD

**Issue by nolros** [creativeorange/gravatar#6]
First, thanks for library. I found that Gravatar::exists() always returns true no matter what address you enter. Could I suggest you add the following as a check as this will return the right bool:

                $email= "name@example.com"; //for testing
                        $gravemail = md5( strtolower( trim( $email ) ) );
                        $gravImage = "http://www.gravatar.com/avatar/".$gravemail;
                        $gravcheck = "http://www.gravatar.com/avatar/".$gravemail."?d=404";
                        $response = get_headers($gravcheck);
                        print_r($response);
                        if ($response[0] != "HTTP/1.0 404 Not Found"){
                            echo('FOUND');
                            $img = $gravImage;
                        } else {
                            echo('FOUND');
                            // execute fallback
                        }

**Comment by creativeorange** [comment]
Could you please create a pull request for this? If not, I will take a look at it this weekend.

**Comment by woodspire** [comment]
Each time you call Gravatar::exists or Gratavar::get, you need to call before ::fallback(false) to be sure to get a 404.
